# Generated by Django 2.1.7 on 2019-03-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20190320_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='has_seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes', models.IntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='has_seasons',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.season'),
        ),
        migrations.AlterUniqueTogether(
            name='has_seasons',
            unique_together={('episodes', 'anime', 'season')},
        ),
    ]
