# Generated by Django 2.1.7 on 2019-03-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.NullBooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.CharField(max_length=255, null=True)),
                ('contribution', models.IntegerField(default=0)),
                ('special', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.special')),
            ],
        ),
    ]
