# Generated by Django 2.1.7 on 2019-03-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='picture',
            new_name='image',
        ),
    ]
