# Generated by Django 2.1.7 on 2019-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190419_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='Root', max_length=255),
            preserve_default=False,
        ),
    ]
