# Generated by Django 2.1.7 on 2019-04-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='special',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.special'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
