# Generated by Django 2.1.7 on 2019-04-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190419_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='id',
        ),
        migrations.AddField(
            model_name='special',
            name='username',
            field=models.CharField(default='*', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='special',
            name='type',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.special'),
        ),
    ]
