# Generated by Django 2.1.7 on 2019-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190419_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='special',
            field=models.NullBooleanField(default=None),
        ),
    ]
